# GitHub config
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# Allow drafts?
publish_mode: editorial_workflow

# Media uploads
media_folder: "img/uploads"
public_folder: "/_site/img/uploads"

# Collections
collections:
  - name: "articles" # Used in routes, e.g., /admin/collections/articles
    label: "Articles" # Used in the UI
    folder: "articles" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "SEO Title (optional)", name: "seo_title", widget: "string"}
      - {label: "Short Title (optional)", name: "short_title", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "SEO Description (optional)", name: "seo_description", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Cover Image (optional)", name: "cover_image", widget: "image"}
      - {label: "Cover Image Alt Text (optional)", name: "cover_image_alt", widget: "string"}
      - {label: "Content", name: "body", widget: "markdown"}
      # TODO: Add Topics and Tags as arrays